### ISSUE TITLE
[Feature] Add separate log file with errors

### ISSUE THREAD

**Issue by Skachuk** [WikiTransformationProject/wikitraccs-releases#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Proposal

Hello Heinrich-Ulbricht
For our company, having a separate log file with errors after migration will be great.
We have a lot of pages and the ability to see and find fast what is wrong is important for us.
Thank you.
WBR

### Confluence Version

Confluence 7 (7.18 or newer)

### Confluence Data Center?

- [ ] This is about Confluence Data Center

**Comment by heinrich-ulbricht** [comment]
@Skachuk The [common log files](https://www.wikitransformationproject.com/docs/troubleshooting/troubleshooting-strategies/#common-log-files) contain all log messages, including warnings and errors. When troubleshooting, you can filter those by the **WRN** or **ERR** markers, that indicate warnings and errors.

What is your expectation instead? Having a separate log file containing all error messages (that are also in the big common log files)? Are messages missing, that you did not find in the big log files but would expect to be there? Or is this more of a documentation issue, that you are not really sure where to look? After all there are the [common log files](https://www.wikitransformationproject.com/docs/troubleshooting/troubleshooting-strategies/#common-log-files), the [progress log files](https://www.wikitransformationproject.com/docs/reference/monitoring-confluence-to-sharepoint-migration-progress) and the [page migration success view](https://www.wikitransformationproject.com/blog/2022/10/22/measuring-page-migration-success). Together, those paint the whole picture.

**Comment by heinrich-ulbricht** [comment]
The latest WikiTraccs (pre)release adds a separate log file for warnings and errors.
