### ISSUE TITLE
[Feature] Replace "Display Children" Macro with SharePoint links

### ISSUE THREAD

**Issue by timo-rempe** [WikiTransformationProject/wikitraccs-releases#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Proposal

Having the "Display Children" Macro be transformed into SharePoint links to those pages would be very helpful to navigate the migration result. 

![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/162319872/0394326c-005c-4b73-b31f-4e6e9745568b)

Of course, WikiPakk offers features to navigate the pages in SharePoint but this would offer up a middle-ground where it requires some manual maintenance but navigation is possible if prepared in Confluence beforehand.

### Confluence Version

Confluence 7 (7.18 or newer)

### Confluence Data Center?

- [ ] This is about Confluence Data Center

**Comment by heinrich-ulbricht** [comment]
@timo-rempe Do you have a static list of links in mind? A snapshot of what the macro shows in Confluence at migration time? This would not update, when adding/removing "child pages" in SharePoint.

**Comment by timo-rempe** [comment]
@heinrich-ulbricht That is what I had in mind! Here's what the macro looks like:
![grafik](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/162319872/55ce8c6b-c61c-4a94-aeb5-91201a78c655)
![grafik](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/162319872/e3441ab3-85ef-4a4e-8956-0d226cea4976)
![grafik](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/162319872/b23ecd4e-d4ff-4284-b4b0-5092b90a2de5)

[Here ](https://confluence.atlassian.com/conf719/children-display-macro-1157466700.html) is the documentation of this macro.

**Comment by timo-rempe** [comment]
In a similar vein, there is the "Page Properties Report"-Macro, which gives a good overview of the child pages, that being a static table would be amazing!
https://confluence.atlassian.com/doc/page-properties-report-macro-186089616.html

**Comment by heinrich-ulbricht** [comment]
The Display Children macro is replaced by SharePoint links as of the latest [WikiTraccs prerelease](https://github.com/WikiTransformationProject/wikitraccs-releases/releases).
