### ISSUE TITLE
WikiTraccs.Console.exe error

### ISSUE THREAD

**Issue by Oli-UCL** [WikiTransformationProject/wikitraccs-releases#126]
Hi,
 
When running the WikiTraccsConole.exe, I receive the attached error:
![WikiTraccsConole Error](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/170094128/826d74b0-669f-401e-bc1b-3a4ce2885b45)

[010 09:28:21 ERR   ] Uncaught exception; logging and terminating in 30 seconds | WikiTraccs.Console.Program
WikiTraccs.Shared.Interfaces.WikiTraccsException: No or more than one transformation mapping found in configuration. Add EXACTLY one, more than one is currently not supported.
   at WikiTraccs.Console.ConfluenceMonitor.GoAsync(CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Console/Program.cs:line 109
   at WikiTraccs.Console.Program.gTgV2OWlKx(String[]  ) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Console/Transformation.SharePoint/MappingProviders/HtmlMapping/ElementExtensions.cs:line 119
 

The WikiTraccs console is saved in the C: drive. I have added the license text file.

Please let me know if you require any further information.
 
WikiTraccs Version: 1.16.2
OS Version: Windows 10 Enterprise 10.0.19044

**Comment by heinrich-ulbricht** [comment]
Hi @Oli-UCL,

Configuring via WikiTraccs.Console is not as straightforward as with WikiTracc.GUI. It's complaining that somethings is off in the appsettings.json.

Is there a reason you have to use the Console? Could you try the GUI instead?

The GUI has an option to show the config (that you did in the GUI) as text. You could use that to challenge your config.

**Comment by Oli-UCL** [comment]
Hi,

Thank you for your quick response.

I have been using the GUI. I had added the license key in a text file as per the instructions but when migrating it is still doing so as a trial version.

On The GUI, I noticed it states that the console is not running.

Thought it could be the license key but when running the console, it confirms the license is valid.

Apologies, if this does not make much sense. I am not too familiar with how this works.

**Comment by heinrich-ulbricht** [comment]
No worries, we'll get you unstuck.

First of all: the license makes no difference with regard how GUI and Console work together. So let's ignore that for a moment.

Could you have a look at the quick start tutorial and video, please: https://www.wikitransformationproject.com/docs/getting-started

There are two things that should happen when starting the transformation via the blue GUI that sometimes cause confusion: browser tabs will be opened for you to authenticate with SharePoint - that can happen in the background and you have to bring the browser windows to the foreground. And the blue GUI will start the Console. In rare cases this fails and we would have to look into why.

The quick start describes, how it _should_ work.

Let me know if something works, or not.

**Comment by Oli-UCL** [comment]
Hi,

I did the testing before purchasing. It works fine, it migrates the content.

However, after adding the license and once I had completed a migration, it is still displaying the message: "PAGE CREATED BY TRIAL VERSION OF [WIKITRACCS -- AND CHECK OUT THE SHAREPOINT PAGE TREE".

**Comment by Oli-UCL** [comment]
Hi,

It's working fine now. 

In hindsight, this should've been obvious to me.

Thanks again. Really appreciate the quick response.

**Comment by heinrich-ulbricht** [comment]
Nice! If you like, tell me the one sentence that would've helped you, but is currently missing (and where you'd expect it).

Otherwise: glad it worked.
