### ISSUE TITLE
Links: transform space links

### ISSUE THREAD

**Issue by heinrich-ulbricht** [WikiTransformationProject/wikitraccs-releases#13]

**Comment by heinrich-ulbricht** [comment]
Space links are now transformed based on the configuration in the Space Inventory SharePoint list.

**Comment by haroldvandekamp** [comment]
Great that this is implemented already. 
@heinrich-ulbricht : The documentation at https://www.wikitransformationproject.com/docs/reference/migration-samples/#links-to-content-outside-a-page needs to be updated regarding this.
