### ISSUE TITLE
Cannot get Confluence Spaces

### ISSUE THREAD

**Issue by sys-pw** [WikiTransformationProject/wikitraccs-releases#21]
Hi there,

i'm trying to set up a Test Environment for our Confluence Site. 
But I'm kind of stuck.

Testing the Connection to Confluence works fine, but as soon as i try "Updating space inventory..." i get this error message:
![image](https://user-images.githubusercontent.com/126480635/221572626-e9f9f26b-8300-43a1-9e47-6acf4f7190a2.png)

Here is the logfile:
[WikiTraccs.GUI.debug20230227_anonymous.log](https://github.com/WikiTransformationProject/wikitraccs-releases/files/10840058/WikiTraccs.GUI.debug20230227_anonymous.log)

I'm really can't figure out what i have set up wrong...

**Comment by heinrich-ulbricht** [comment]
This is strange. (_Disclaimer: Confluence Cloud ist not officially supported **yet**, although testing it is fine and migrating should work._)

That being out of the way: Could you try leaving the Advanced cookie names empty? The connection test should succeed as WikiTraccs by default uses both the **JSESSIONID** and the **cloud.session.token** cookies.
![image](https://user-images.githubusercontent.com/3469970/221608622-75153b96-c49a-4c17-bde6-cbd06fd33539.png)

This works in my cloud test environment. Is there anything special about your environment that I should know?

You could also try providing cookies via cookie.txt as described here: https://www.wikitransformationproject.com/docs/troubleshooting/authentication-issues/confluence/#2-provide-cookies-manually

**Comment by sys-pw** [comment]
Tried all of the above, unfortunately still the same result.

Testing the Confluence Connection works fine, trying to update the Space Inventory fails.

What could be things you should know about our environment? 
I can't think of anything special about our Site except that it's cloud based and for Company Users only.

**Comment by heinrich-ulbricht** [comment]
Good question, I'm trying to work out the difference between your environment and my test environment, where it works.

I'll do more tests to hopefully run into the same issue. Thanks for reporting back.

**Comment by heinrich-ulbricht** [comment]
@sys-pw Could you please try the latest release 0.1.3? I could reproduce and fix the issue, at least for my test environment.

**Comment by sys-pw** [comment]
Hi @heinrich-ulbricht 
test with 0.1.3 worked like a charm, thanks for the quick fix!
