### ISSUE TITLE
Error while trying to select space

### ISSUE THREAD

**Issue by frankremedy** [WikiTransformationProject/wikitraccs-releases#22]
Confluence connection verified but when selecting space, it states Confluence connection error.  Could not get data context for Confluence.  I can do nothing.

**Comment by heinrich-ulbricht** [comment]
Hi, which Confluence version are you using?

**Comment by frankremedy** [comment]
Confluence Cloud


Frank Derenne
IT Administrator and Security Officer
***@***.***
Office 
800-975-9517 Ext.737
Remedy Analytics, Inc.
 234 W. Florida Street, Suite 150 
 Milwaukee, WI 53204 
 remedyanalytics.com
​

 Privacy Notice | ​Legal Notice
 
 CONFIDENTIALITY NOTICE: The information contained in this communication, including attachments, may contain privileged and confidential information that is intended only for the exclusive use of the addressee. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us by telephone immediately.
  
 Please be advised that any and all information, comments, analysis, and/or recommendations set forth above relative to the possible impact of COVID-19 on potential insurance coverage or other policy implications are intended solely for informational purposes and should not be relied upon as legal advice. We have no authority to make coverage decisions as that ability rests solely with the issuing carrier. Therefore, all claims should be submitted to the carrier for evaluation. The positions expressed herein are opinions only and are not to be construed as any form of guarantee or warrantee. Finally, given the extremely dynamic and rapidly evolving COVID-19 situation, comments above do not take into account any applicable pending or future legislation introduced with the intent to override, alter or amend current policy language.

**Comment by heinrich-ulbricht** [comment]
Did you enter "...atlassian.net" as Confluence base address, or. "..atlassian.net/wiki"? If the former, could you please try the latter?

**Comment by frankremedy** [comment]
I added /wiki   now it states  'cannot get spaces'   'could not get space information from Confluence.  Check the logs for hints.  Cannot do more'




Frank Derenne
IT Administrator and Security Officer
***@***.***
Office 
800-975-9517 Ext.737
Remedy Analytics, Inc.
 234 W. Florida Street, Suite 150 
 Milwaukee, WI 53204 
 remedyanalytics.com
​

 Privacy Notice | ​Legal Notice
 
 CONFIDENTIALITY NOTICE: The information contained in this communication, including attachments, may contain privileged and confidential information that is intended only for the exclusive use of the addressee. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us by telephone immediately.
  
 Please be advised that any and all information, comments, analysis, and/or recommendations set forth above relative to the possible impact of COVID-19 on potential insurance coverage or other policy implications are intended solely for informational purposes and should not be relied upon as legal advice. We have no authority to make coverage decisions as that ability rests solely with the issuing carrier. Therefore, all claims should be submitted to the carrier for evaluation. The positions expressed herein are opinions only and are not to be construed as any form of guarantee or warrantee. Finally, given the extremely dynamic and rapidly evolving COVID-19 situation, comments above do not take into account any applicable pending or future legislation introduced with the intent to override, alter or amend current policy language.

**Comment by heinrich-ulbricht** [comment]
Not cool, looks like #21. Will investigate further.

**Comment by frankremedy** [comment]
Sounds good - thank you


Frank Derenne
IT Administrator and Security Officer
***@***.***
Office 
800-975-9517 Ext.737
Remedy Analytics, Inc.
 234 W. Florida Street, Suite 150 
 Milwaukee, WI 53204 
 remedyanalytics.com
​

 Privacy Notice | ​Legal Notice
 
 CONFIDENTIALITY NOTICE: The information contained in this communication, including attachments, may contain privileged and confidential information that is intended only for the exclusive use of the addressee. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us by telephone immediately.
  
 Please be advised that any and all information, comments, analysis, and/or recommendations set forth above relative to the possible impact of COVID-19 on potential insurance coverage or other policy implications are intended solely for informational purposes and should not be relied upon as legal advice. We have no authority to make coverage decisions as that ability rests solely with the issuing carrier. Therefore, all claims should be submitted to the carrier for evaluation. The positions expressed herein are opinions only and are not to be construed as any form of guarantee or warrantee. Finally, given the extremely dynamic and rapidly evolving COVID-19 situation, comments above do not take into account any applicable pending or future legislation introduced with the intent to override, alter or amend current policy language.

**Comment by frankremedy** [comment]
It is moving along further   I did have to add /wiki at the end of the Confluence site for it to properly work


Frank Derenne
IT Administrator and Security Officer
***@***.***
Office 
800-975-9517 Ext.737
Remedy Analytics, Inc.
 234 W. Florida Street, Suite 150 
 Milwaukee, WI 53204 
 remedyanalytics.com
​

 Privacy Notice | ​Legal Notice
 
 CONFIDENTIALITY NOTICE: The information contained in this communication, including attachments, may contain privileged and confidential information that is intended only for the exclusive use of the addressee. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us by telephone immediately.
  
 Please be advised that any and all information, comments, analysis, and/or recommendations set forth above relative to the possible impact of COVID-19 on potential insurance coverage or other policy implications are intended solely for informational purposes and should not be relied upon as legal advice. We have no authority to make coverage decisions as that ability rests solely with the issuing carrier. Therefore, all claims should be submitted to the carrier for evaluation. The positions expressed herein are opinions only and are not to be construed as any form of guarantee or warrantee. Finally, given the extremely dynamic and rapidly evolving COVID-19 situation, comments above do not take into account any applicable pending or future legislation introduced with the intent to override, alter or amend current policy language.

**Comment by frankremedy** [comment]
So It asks to open space inventory and select which I did  but then does nothing.  Am I missing a step?

[cid:3e3d4963-6b87-4b40-b4f2-ea2bd7f5a171]

[cid:fa4553cb-fd4a-4a48-989a-90621d9c4c25]

Frank Derenne
IT Administrator and Security Officer
***@***.***
Office 
800-975-9517 Ext.737
Remedy Analytics, Inc.
 234 W. Florida Street, Suite 150 
 Milwaukee, WI 53204 
 remedyanalytics.com
​

 Privacy Notice | ​Legal Notice
 
 CONFIDENTIALITY NOTICE: The information contained in this communication, including attachments, may contain privileged and confidential information that is intended only for the exclusive use of the addressee. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us by telephone immediately.
  
 Please be advised that any and all information, comments, analysis, and/or recommendations set forth above relative to the possible impact of COVID-19 on potential insurance coverage or other policy implications are intended solely for informational purposes and should not be relied upon as legal advice. We have no authority to make coverage decisions as that ability rests solely with the issuing carrier. Therefore, all claims should be submitted to the carrier for evaluation. The positions expressed herein are opinions only and are not to be construed as any form of guarantee or warrantee. Finally, given the extremely dynamic and rapidly evolving COVID-19 situation, comments above do not take into account any applicable pending or future legislation introduced with the intent to override, alter or amend current policy language.
 
________________________________

**Comment by heinrich-ulbricht** [comment]
@frankremedy 

Thanks for the feedback. The /wiki thing is now tracked here: #28.

In the space inventory set the check mark for spaces to be migrated:

![image](https://user-images.githubusercontent.com/3469970/222465809-08079492-e8fd-40c3-a128-d0c140b440b0.png)

Then go back to WikiTraccs.GUI and select **Start transformation**:
![image](https://user-images.githubusercontent.com/3469970/222466169-95574ff9-3454-4c47-b28f-c9ea4ec958ae.png)

It should now recognize your selected spaces and start with the migration.

(If the **Start transformation** button is disabled, close any WikiTraccs.Console windows first that are still running.)

**Comment by frankremedy** [comment]
Running!  thank you for your help!

Frank Derenne
IT Administrator and Security Officer
***@***.***
Office 
800-975-9517 Ext.737
Remedy Analytics, Inc.
 234 W. Florida Street, Suite 150 
 Milwaukee, WI 53204 
 remedyanalytics.com
​

 Privacy Notice | ​Legal Notice
 
 CONFIDENTIALITY NOTICE: The information contained in this communication, including attachments, may contain privileged and confidential information that is intended only for the exclusive use of the addressee. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us by telephone immediately.
  
 Please be advised that any and all information, comments, analysis, and/or recommendations set forth above relative to the possible impact of COVID-19 on potential insurance coverage or other policy implications are intended solely for informational purposes and should not be relied upon as legal advice. We have no authority to make coverage decisions as that ability rests solely with the issuing carrier. Therefore, all claims should be submitted to the carrier for evaluation. The positions expressed herein are opinions only and are not to be construed as any form of guarantee or warrantee. Finally, given the extremely dynamic and rapidly evolving COVID-19 situation, comments above do not take into account any applicable pending or future legislation introduced with the intent to override, alter or amend current policy language.
 
________________________________

**Comment by heinrich-ulbricht** [comment]
@frankremedy Perfect!

Please don't hesitate to create new issues for problems you find in Confluence Cloud, I'm collecting those here -> https://github.com/WikiTransformationProject/wikitraccs-releases/issues/24
