### ISSUE TITLE
Problem with Wikitraccs

### ISSUE THREAD

**Issue by Paulll3** [WikiTransformationProject/wikitraccs-releases#35]
pressing "Update spaceinventory and Wikitraccs side" in **interactive login** mode leads to this:
<img width="360" alt="meldung" src="https://user-images.githubusercontent.com/128603481/226911083-79cd372c-2903-43c6-aaff-5cd474ce363b.png">

pressing "Update spaceinventory and Wikitraccs side" in **anonymus** mode leads to this:
![image](https://user-images.githubusercontent.com/128603481/226912069-46126eed-6915-46ca-a3e2-3a7029c9b0b6.png)

I have had no problems with the Steps before.
Confluence version:  5.8.15

**Comment by heinrich-ulbricht** [comment]
Could you please post the anonymized version of your Confluence URL? I want to have a look at the structure.

And please have a look at the log file in the `/logs` folder. It might contain helpful error messages.

**Comment by heinrich-ulbricht** [comment]
Could you please send the log file to issue35@wikitransformationproject.com ? I'd like to have a look.

**Comment by Paulll3** [comment]
I have sent you an email

**Comment by heinrich-ulbricht** [comment]
@Paulll3 Thank you very much for the log file. The endpoint WikiTraccs uses to look up the current user does not exist in Confluence 5. So I guess it's not compatible with Confluence 5, sorry. I updated the documentation to properly reflect this.

Just for the record, I had a look at the EOL date of Confluence 5.8.15 and it seems to be 2017. Would be a good time to move away, but alas. Upgrading might be an option, but the licensing model changed with Confluence 6, so not sure if that is an option at all or would force you to upgrade to Confluence 7 as well. I'm afraid but it looks like WikiTraccs can't help you here :(

**Comment by Paulll3** [comment]
Thank you for the help and the information. It was worth a try.
