### ISSUE TITLE
Making no progress

### ISSUE THREAD

**Issue by cder-omarriott** [WikiTransformationProject/wikitraccs-releases#36]
I migrated a confluence space to a SharePoint site using the tool.
Since I migrated there have been changes made on confluence.
I have attempted remigration of the data however WikiTracc's gets stuck
`[007 10:22:38 DBG  IT-Manual] [https://confluence.cdergroup.co.uk] Will now schedule page retrieval for space 'IM'; checking 335 pages, got 149 to ignore, 0 to create and 186 to (potentially) update | WikiTraccs.Console.ConfluenceMonitors.ConfluenceContentRetriever`
As I write this it is 13:30:45 and no progress has happened

**Comment by heinrich-ulbricht** [comment]
@cder-omarriott Hi, WikiTraccs does not overwrite pages. But you can simply delete the pages in SharePoint and WikiTraccs will create them again.

So

- delete the pages
- restart WikiTraccs
- start the migration again 

...and they should appear.

**Comment by heinrich-ulbricht** [comment]
Note: starting with release v1.1.x it has gotten easier to track which pages are yet-to-be-migrated and which need an update -> [Monitoring Confluence to SharePoint Migration Progress](https://www.wikitransformationproject.com/docs/reference/monitoring-confluence-to-sharepoint-migration-progress).

The next step of course would be an update mode.

**Comment by heinrich-ulbricht** [comment]
The update mode #47 implementation has been scheduled for the June/July timeframe.
