### ISSUE TITLE
Error "Could not get data context for Confluence. I can do nothing.". I did all things like in the documentation but it did not work.

### ISSUE THREAD

**Issue by christmiLBT** [WikiTransformationProject/wikitraccs-releases#50]
Hello we`ll try this tool before we will buy it. But in the configuration there is always an error and i have no idea what`s the reason for it. Is it possible to get support (sure we will pay for it ).  The Error is "COULD NOT GET DATA CONTEXT FOR CONFLUENCE. I CAN DO NOTHING

**Comment by heinrich-ulbricht** [comment]
@christmiLBT Nice. This is the second time somebody ran into this trap, this should be handled more gracefully by WikiTraccs. Glad you got it working.

The **WikiTraccs site** in step 2/4 is like the "engine room" for WikiTraccs, where certain data related to the migration is stored. This site could be removed after finishing the migration.

The **Default target site** in step 4/4 is where the content from Confluence is migrated to.

You're welcome :)

**Comment by heinrich-ulbricht** [comment]
Closing this ticket since the original issue is resolved.
