### ISSUE TITLE
Support for .MP4 files

### ISSUE THREAD

**Issue by RobinAtRestore** [WikiTransformationProject/wikitraccs-releases#51]
Hi

The trial version of WikiTraccs doesn't support the transfer of MP4 files, is this a restriction in the trial version or something that is not supported at all ?

If it's the latter (not supported) then is there a plan to add this support at all ?

Thanks

Robin

**Comment by heinrich-ulbricht** [comment]
@RobinAtRestore No this is strange.

Somehow the video is - technically - embedded as image!?

I don't know how to reproduce this. When I drag and drop an MP4 file to a Confluence page it looks like this, here one time as preview, and another time as link:

![video-preview](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/3469970/66bfd0be-a63d-4a87-9c0a-99781ecc57a6)

The storage format looks like this:

```xml
<p>
    <ac:structured-macro ac:name="view-file" ac:schema-version="1"
        ac:macro-id="41cf12c9-72c9-4b7c-8dc6-ef108f8f0621">
        <ac:parameter ac:name="name">
            <ri:attachment ri:filename="test.mp4" />
        </ac:parameter>
        <ac:parameter ac:name="height">250</ac:parameter>
    </ac:structured-macro>
</p>
<p>
    <ac:link>
        <ri:attachment ri:filename="test.mp4" />
    </ac:link>
</p>
```

This works and looks as expected in SharePoint:

![mp4embed2](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/3469970/3f890a4d-fce0-45fb-91d5-50ab5ab52894)


Could you send me the storage format of an affected page please ( contact@wikitransformationproject.com ) - hopefully the following option is present: 

![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/3469970/aae68eb8-8624-4d25-a15f-fd6f54a38bfc)

This should make things clearer.

**Comment by heinrich-ulbricht** [comment]
After reviewing the storage format I can confirm that the following construct in the Confluence page causes the issue:

```xml
<ac:image ac:align="center" ac:layout="center" ac:original-height="1080" ac:original-width="1920">
   <ri:attachment ri:filename="Create a Customer Demo.mp4" ri:version-at-save="1" />
</ac:image>
```

This is an **image** element referencing a **video** file. WikiTraccs does not know yet that this is even possible. That's something for a next release to be handled properly. It should fall back to video migration behavior, which is: inserting a link to the video attachment into the SharePoint page.

**Comment by heinrich-ulbricht** [comment]
Handling of image elements that in fact point to a video has been added in the [latest release v1.3.13](https://github.com/WikiTransformationProject/wikitraccs-releases). Could you please try re-migrating some of the affected pages with the new version? (Delete them in SharePoint, before migrating again.)

The implementation is based on the storage format I got from you/your colleague. Let's see if it covers all affected cases - please report back. Thanks!

**Comment by RobinAtRestore** [comment]
Hi

i can confirm that after the latest upgrade, the file is now linked on the migrated page:

![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/132668133/0ca80f58-61fd-4ed6-9bae-72d78eb346c2)

Thanks for your help on this.

Robin

**Comment by heinrich-ulbricht** [comment]
@RobinAtRestore You're welcome, thanks for the feedback.
