### ISSUE TITLE
Pages translated to German

### ISSUE THREAD

**Issue by craigjm** [WikiTransformationProject/wikitraccs-releases#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For one site in our test migrations, some pages were translated to German in the migration to SharePoint. As far as I can tell, our language is set to English in Confluence and SharePoint. This is the only site I have noticed the behavior in so far. I tried a new migration to see if it was just a fluke, but the behavior was repeated the second time as well. I am emailing you the relevant log files.

### Expected Behavior

I was expecting the migration to keep the English language from the source Confluence pages.

### WikiTraccs Version

v1.3.13

### Confluence Version

Confluence 7

**Comment by heinrich-ulbricht** [comment]
Interesting and strange. That's the attachemnts macro, that gets special treatment and its content is delivered by Confluence. Is anything else in German on those pages, apart from the attachments macro? Is the Scroll Translations macro in use? And could you please send the storage format for that page over, for that page? Thank you!

**Comment by heinrich-ulbricht** [comment]
@craigjm I found something and can reproduce the behavior you see, for the attachments macro.

Could you please open the user settings for the account used for the migration?

This is probably how it's configured right now:
![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/3469970/0a6511a1-6ce9-4c17-8fdd-4965a7dfbc11)

Change this to be explicitly English:

![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/3469970/d92eebaf-884e-406f-a3e5-0c8a5a875390)

This solved the issue for me and switched the content to English.

Background: the contents of the attachments macro is rendered by Confluence, WikiTraccs takes this output and puts it into the migrated page. Confluence has logic built in to figure out the language that you might want to see and this is forcing it to choose English.

**Comment by craigjm** [comment]
Yes, this resolved the translation issue for me. Thank you!
