### ISSUE TITLE
[Feature] Close Console when finished

### ISSUE THREAD

**Issue by PretoPlasma** [WikiTransformationProject/wikitraccs-releases#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Proposal

When trying to automate the execution wikitraccs.console (using robot framework)  the console does not close when migration is done (based on appsettings.json). This leads into a robot who is running infinetly.
How can I detect that the migration is finished?
Or is there an argument to pass that the console closes on end of migration?

### Confluence Version

Confluence 7

**Comment by heinrich-ulbricht** [comment]
Hi @PretoPlasma, that is correct, the Console currently does not close automatically. Originally it was designed as a process that can take new migration orders at any time. But the current mode is more like: run, close, run again, close. Which is not feasible for automating things.

Just out of curiosity, what is your automation use case? I had one or two requests in the past that suggested that synchronizing Confluence to SharePoint regularly might be valuable. So far I did not understand what the goal of such a synchronization would be. Is it permission-related? Licensing optimization? Publishing? I'd be glad to gain some insights to better support those scenarios in the future.

**Comment by PretoPlasma** [comment]
Hi @heinrich-ulbricht, it is permission related and license optimization. We face a space-by-space migration as pre-procedures like permissions and space preparation need to be completed before the migration makes sense. And to not block the robot license with wikitraccs running in idle mode we would like to start wikitraccs only when a space is ready for migration, migrate this single space and then end this part of the migration, if this makes sense for you. So what about having an argument passed to console.exe e.c. --terminateOnEnd that the console let terminate the session after the miration work is done?! Do you think this is possible to be implemented asap?

**Comment by heinrich-ulbricht** [comment]
I see, thanks for the details. As a workaround you can look for one of the [progress log files](https://www.wikitransformationproject.com/docs/reference/monitoring-confluence-to-sharepoint-migration-progress/) that WikiTraccs creates when going into idle mode, and kill the process.

This is only a workaround, but works immediately. I'll try to slip a better solution into one of the upcoming releases, but are hesitant to give an ETA.

**Comment by PretoPlasma** [comment]
Thanks @heinrich-ulbricht for your quick reply. I am going to test that and let you know.

**Comment by AlexAuras** [comment]
@heinrich-ulbricht you probably want to update the [Known Issues ](https://www.wikitransformationproject.com/docs/reference/known-issues/#current-limitations-of-wikitraccsconsole) page on your docu accordingly.

**Comment by heinrich-ulbricht** [comment]
@AlexAuras I sure want to, thank you! Fixed.
