### ISSUE TITLE
'Could not get all required confluence auth cookies error on particular devices

### ISSUE THREAD

**Issue by cwaterman01** [WikiTransformationProject/wikitraccs-releases#65]
When I'm on step 3 - the configuration validation - I press the button to 'Test confluence connection again' and Chrome will open, load up confluence and go to the search screen for confluence (spacelocationname.atlassian.net/wiki/search) and then do nothing. 

After 5 minutes or if I close the Chrome web browser then I get an error which tells me 'could not get all required confluence auth cookies. Check advanced configuration, and make sure no leftover automated browsers are open. Then try again. 
![image (1)](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/137119828/d4cc37b0-135f-4fe6-b598-38aae0462354)

One colleague of mine tried it and got the same error and another colleague of mine tried it and was able to do the transfer. 

What can I do to troubleshoot or identify what the issue is? Any idea on the solution?

**Comment by heinrich-ulbricht** [comment]
@cwaterman01 I saw issues with the browser based login and Confluence Cloud in the past depending on the account type.

Are there differences for the accounts that were used? Like some from Azure AD, some cloud-native, some with third-party IDP? This could make a difference.

You could have a look in the [common log files](https://www.wikitransformationproject.com/docs/troubleshooting/troubleshooting-strategies/#common-log-files), WikiTraccs usually logs what it's waiting for, or send them over to contact@wikitransformationproject.com and I'll have a look.

Ultimately the authentication mechanism for Cloud has to change, but that is something for the roadmap -> #24

**Comment by cwaterman01** [comment]
Thanks Heinrich - we use AD to login and we're quite sure we have SSO setup. 

Here are the log files attached. 

[WikiTraccs.GUI.debug20230616.log](https://github.com/WikiTransformationProject/wikitraccs-releases/files/11827054/WikiTraccs.GUI.debug20230616.log)

**Comment by heinrich-ulbricht** [comment]
Thanks for the log! Seems like the current assumption about cookies in Confluence Cloud is not correct.

WikiTraccs expects **cloud.session.token** to be present, while it also can be **tenant.session.token** (or both). This needs an adjustment in the detection logic.

**Comment by heinrich-ulbricht** [comment]
@cwaterman01 I could reproduce the issue and the latest [release v1.6.8](https://github.com/WikiTransformationProject/wikitraccs-releases/releases) addresses this. Could you give it a try please?

**Comment by cwaterman01** [comment]
Hey Heinrich - I was able to make some progress but another error has appeared instead.

Tested tool (1.68) and I was able to test and have a successful connection to the base confluence site (https://watercarestp.atlassian.net/wiki ) but not the exact TDL library I wanted ( https://watercarestp.atlassian.net/wiki/spaces/TDL)

It loads up and logs in to confluence successfully but comes up with the following error;

![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/137119828/100baa6a-3377-4215-b0b7-b345a7c1bcde)

I can't find any logs? Let me know if there's anything else you need!

**Comment by heinrich-ulbricht** [comment]
Good, progress!

Now you need to change the URL in the Confluence base address field. The base address ends after **/wiki**. Remove the rest and it should connect.

The source space is chosen in a later step in the space inventory list.
