### ISSUE TITLE
WikiTraccs.GUI halts on "Test Confluence connection"

### ISSUE THREAD

**Issue by hopeforgood** [WikiTransformationProject/wikitraccs-releases#72]
Hi,
I am testing the WikiTraccs.GUI and I am following your guide "WikiTraccs Migration Quick Start - First Confluence Migration" video.
And got almost everything just fine until video time 10:20 (Authentication). *>>
When I hit then "Test Confluence connection" button it does open my browser to check confluence site, and that works fine, but after that the gui is fineshed/terminated.
Can you please help me ?
I know we will have a new demonstration on Aug 8, and before that I would like to try the tool by myself.
This is Ronaldo Akamine and I am from Linda's team.

Thank you!!

*>>at 6:30 "Pnp Powershell" I had to use the commands bellow:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Install-PackageProvider -Name nuget -MinimumVersion 2.8.5.201 -force
Install-Module -Name "PnP.PowerShell" -RequiredVersion 1.12.0 -Force -AllowClobber

From link:
https://learn.microsoft.com/en-us/answers/questions/1196279/import-module-could-not-load-file-or-assembly-syst

Because with just "Import-Module PnP.PowerShell" I was getting error bellow for command "Register-PnPManagementShellAccess":
Import-Module : Could not load file or assembly 'System.Management.Automation

**Comment by hopeforgood** [comment]
The button to test "Test SharePoint connetion" works like a charm:
![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/140747685/ff964564-2105-40e6-881b-adcf0b61f2b7)

**Comment by hopeforgood** [comment]
I leave confluence connection untested and tried buttons:
"Open space inventory to choose source spaces": and it tries to open an invalid url:
https://7xtrxb.sharepoint.com/sites/WikiTraccsStore/Lists/Confluence%20Space%20Inventory%20WikiTraccs
I believe probably confluence connection test failed in previous step.

Also tried button "Start Transformation" and the gui just halts and is terminated

**Comment by hopeforgood** [comment]
Forget about it. I got the problem here because used not the root link url.
After using the root link correctly for confluence (source) the checn Confluence button worked.
![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/140747685/4f0b51d0-f791-4e3c-99b1-08976399a7d8)

**Comment by heinrich-ulbricht** [comment]
@hopeforgood Love it how you are tackling those issues! Is there any issue left or are you making progress?

**Comment by hopeforgood** [comment]
Hi, Thanks!
Migrating all now
Still running lets see

**Comment by hopeforgood** [comment]
One question I already have is how to setup the migration to properly generate the page tree hierarchy ?
![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/140747685/d328c8e8-8199-42ac-af5f-77058506c42d)

**Comment by heinrich-ulbricht** [comment]
@hopeforgood Confluence page tree hierarchy info is migrated by default. Each migrated SharePoint page has Confluence page ID and parent page ID attached as field values in the Pages library.

If you want a ready-made solution to visualize this data in SharePoint as page tree, you can try [WikiPakk](https://www.wikipakk.com). It solves exactly this requirement.

**Comment by heinrich-ulbricht** [comment]
I'm going to close this issue as you could resolve it by yourself. Please don't hesitate to open a new one if there is something wrong, or start a discussion for general questions.

**Comment by hopeforgood** [comment]
Ok
Thank you Heinrich!
