### ISSUE TITLE
ChromeDriver version not found for Chrome version 115.0.5790

### ISSUE THREAD

**Issue by sweetbojangles** [WikiTransformationProject/wikitraccs-releases#74]
Have tried in both the Console app and the UI app, both getting same exception.

I specified the chrome.exe path in the appsettings.json file for the Console app to used 115.0.5790.102 (chrome.exe and chromedriver.exe), but with the same exception.  I actually put the chromedriver.exe in all folders per WikiTraccs suggestion.

Looking for other suggestions on how to get past this error

**Comment by heinrich-ulbricht** [comment]
This sounds like #73. Which version pf WikiTraccs are you using? The latest release should work.

**Comment by sweetbojangles** [comment]
thanks for pointing me to #73. looks like that has resolved the issues
