### ISSUE TITLE
[Error] Unexpected character encountered while parsing value: <. Path '', line 0, positon 0.

### ISSUE THREAD

**Issue by gitdeakin** [WikiTransformationProject/wikitraccs-releases#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to test confluence connection, after logging in, it initially shows this message:
![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/4831116/ca260a12-447d-4870-8ca2-fea836892159)

When I press 'Close' it then shows this error:
![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/4831116/0c3bc8d5-df5c-4061-9bb9-03b4de8716a6)

I have tried:
- Adding `"SkipConfluenceContextPathCookiePathMatching": true` to `appsettings.json`
- Manually adding cookies in `cookies.txt`
- Adding `"AjsRemoteUserKey"` to `appsettings.json`

But the error still persists.

Seems like a `DeserializeObject` issue?

### Expected Behavior

It is expected that the user is retrieved 

### WikiTraccs Version

1.6.35

### Confluence Version

Confluence 6

### Confluence Data Center?

- [ ] This is about Confluence Data Center

**Comment by heinrich-ulbricht** [comment]
@gitdeakin Strange. Could you send the [common log files](https://www.wikitransformationproject.com/docs/troubleshooting/troubleshooting-strategies/#common-log-files) please of WikiTraccs.GUI please to contact - at - wikitransformationproject.com

The logs should show which Confluence endpoint it uses and where it fails.

**Comment by gitdeakin** [comment]
@heinrich-ulbricht Sent

**Comment by heinrich-ulbricht** [comment]
Further testing by @gitdeakin showed that a VPN seemed to cause the issue. Disabling the VPN made the issue go away. The root cause is unknown, though. Will keep an eye on that. Thanks for helping diagnose this!
