### ISSUE TITLE
[Feature] What are the limitations on using the Free Eval ?

### ISSUE THREAD

**Issue by mrc1313** [WikiTransformationProject/wikitraccs-releases#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Proposal

Eval limitations

### Confluence Version

None

### Confluence Data Center?

- [ ] This is about Confluence Data Center

**Comment by heinrich-ulbricht** [comment]
The answer to this question has been added to the [WikiTraccs FAQ](https://www.wikitransformationproject.com/docs/reference/wikitraccs-faq/#q-what-limitations-are-there-on-using-the-free-eval).
