### ISSUE TITLE
[Bug] WikiTraccs Console adds files to page attachments not belonging to page

### ISSUE THREAD

**Issue by PretoPlasma** [WikiTransformationProject/wikitraccs-releases#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We run WikiTraccs Console wrapped around rpa bot. After last run we were informed by our customer that a page contains page attachments which do not belong to the source page.

### Expected Behavior

We would expect that page attachments contain files belonging to source page only.

### WikiTraccs Version

v1.7.4

### Confluence Version

Confluence 7 (up to 7.17)

### Confluence Data Center?

- [ ] This is about Confluence Data Center

### Relevant log output or page storage format

```shell
unsure which part of the log file is necessary
```

**Comment by heinrich-ulbricht** [comment]
WikiTraccs migrates all attachments of a page, whether they are linked to from the page content or not. This includes attachemtns only visible via the paperclip symbol for a page.

Might that be the case here?

If not: can they identify the other page the unexpected attachments are from?

To diagnose this further I need the page ID of the source Confluence page, the page ID of the page the unexpected attachment is from, and the [progress log files](https://www.wikitransformationproject.com/docs/reference/monitoring-confluence-to-sharepoint-migration-progress/#using-progress-log-files-to-get-insights) from the migration run that creates those pages in SharePoint.

**Comment by heinrich-ulbricht** [comment]
@PretoPlasma Thanks for the feedback, that is good news.
