### ISSUE TITLE
[Bug] WikiTraccs Migration creates unneccessary?! columns

### ISSUE THREAD

**Issue by PretoPlasma** [WikiTransformationProject/wikitraccs-releases#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We investigated an issue where a confluence page with a standard filter-enabled two-columns table was migrated to sharepoint having first and last column like the source but in between 13 additional columns (we do not know where do they come from) containing a "⇐🚧" without any other information.

Another page based on same layout (two-column table, etc.) was migrated as it should be.

Migrated page 1:
- confluence (source)
 ![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/107237119/43e9e632-fccc-4067-8278-ac3a3763a0f3)

- sharepoint (target)
![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/107237119/cc02e113-e505-4b10-80d8-093e89323654)

Migratet page 2:
- confluence (source)
![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/107237119/31eaa099-4500-429b-8a76-800b152fa6f9)

- sharepoint (target)
![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/107237119/1e5fa590-631f-4d48-b2f5-7a4da6b5a5c7)

### Expected Behavior

We would expect that in both page migrations the result would be the same:
having a two-column table --> left column containing text, right column containing pictures.

### WikiTraccs Version

v1.7.4

### Confluence Version

Confluence 7 (up to 7.17)

### Confluence Data Center?

- [ ] This is about Confluence Data Center

**Comment by heinrich-ulbricht** [comment]
@PretoPlasma This might be a case of **merged table cells**. SharePoint does **not** support merged table cells and they will be present - unmerged - in SharePoint.

This is a limitation of SharePoint Online. Any table cell that was merged in Confluence is marked with "⇐🚧" (with different arrow directions) to indicate which direction this cell was merged - here multiple cells were merged with a cell on the left, probably in the first column.

I'd like to check the storage format of this page though, if my assumption is correct and if anything could be done to improve the output. If you'd like me to have a look please send the storage format of this page to contact @ wikitransformationproject.com. Here's how to get the storage format: [Get the Confluence storage format](https://www.wikitransformationproject.com/docs/troubleshooting/troubleshooting-strategies/get-confluence-storage-format).

**Comment by PretoPlasma** [comment]
@heinrich-ulbricht thank you very much for your quick and precise support.

And many thanks for that hint: It is absolutely right that there is a difference in the storage format of these two pages. Digging into it we found out that there is columnspan difference from 14:1.

So we can savely close this one. Have a nice day!
