### ISSUE TITLE
[Issue]  Cannot find WikiTraccs companion application

### ISSUE THREAD

**Issue by Skachuk** [WikiTransformationProject/wikitraccs-releases#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We faced a problem in 3 step: "Cannot find WikiTraccs companion application"

### Expected Behavior

Could you please explain what it means and how we can solve this issue?

### WikiTraccs Version

1.8.4 and 1.7.6

### Confluence Version

Confluence 7 (7.18 or newer)

### Confluence Data Center?

- [ ] This is about Confluence Data Center

**Comment by heinrich-ulbricht** [comment]
WikiTraccs comes with two console applications - **WikiTraccs.GUI** and **WikiTraccs.Console**.

WikiTraccs.GUI is mainly for easy configuration. When starting the migration, it passes the configuration you made to WikiTraccs.Console.

The zip release you download contains those two applications:

![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/3469970/0c3652df-cbd3-4b51-ad41-15c83107330a)

When you extract the zip file, this folder structure needs to be intact. WikiTraccs.GUI expectes WikiTraccs.Console to be in a folder adjacent to itself. Starting from the location of its own `WikiTraccs.GUI.exe` it "goes one folder level up", searches for a folder called "WikiTraccs.Console" and expects the `WikiTraccs.Console.exe` to be in there.

When it cannot find WikiTraccs.Console.exe at the expected location it shows the **Cannot find WikiTraccs companion application** error, that you see.

There might be different causes:

- folders have been renamed or removed
- all files have been extracted to the same folder (flat, without hierarchy)
- a security tool blocks WikiTraccs.GUI.exe from accessing WikiTraccs.Console.exe

@Skachuk does this help? If not, please check the [common log files](https://www.wikitransformationproject.com/docs/troubleshooting/troubleshooting-strategies/#common-log-files) for errors and/or send them to contact @ wikitransformationproject.com and I'll have a look.

**Comment by Skachuk** [comment]
Thank you! This helps us.
