### ISSUE TITLE
Start transfromation close the automated open window... no action. 

### ISSUE THREAD

**Issue by antonioferruztui** [WikiTransformationProject/wikitraccs-releases#94]
Hello, 
I m on a trial of your tools evaluating it for our migration to sharepoint from confluence. 

Everything looks fine until I click Start transformation , then a window open and close. nothing happen.. 

Do you know what might be the cause of this ?

Antonio

**Comment by heinrich-ulbricht** [comment]
@antonioferruztui I had a similar effect recently with another client. The problem there was that WikiTraccs.Console was blocked from running.

WikiTraccs.GUI.exe starts WikiTraccs.Console.exe to perform the actual migration. Could you please check that WikiTraccs.Console.exe is unblocked? You can find it in the WikiTraccs.Console folder.

Please perform the following steps:

1. Open Microsoft Windows Explorer to locate **WikiTraccs.Console.exe**
2. Select **WikiTraccs.Console.exe** with the right mouse button and choose **Properties**
3. Choose **Unblock** in the lower right corner of the resulting dialog(*)
4. Select **OK** to close the dialog

(*) If the Unblock button or option is not present, the file is not blocked.

Let me know if that helps.

**Comment by antonioferruztui** [comment]
Looks like that was the issue. Thanks for your help!

Antonio

De: Heinrich Ulbricht ***@***.***>
Enviado el: martes, 24 de octubre de 2023 22:20
Para: WikiTransformationProject/wikitraccs-releases ***@***.***>
CC: Antonio Ferruz ***@***.***>; Mention ***@***.***>
Asunto: Re: [WikiTransformationProject/wikitraccs-releases] Start transfromation close the automated open window... no action. (Issue #94)


@antonioferruztui<https://github.com/antonioferruztui> I had a similar effect recently with another client. The problem there was that WikiTraccs.Console was blocked from running.

WikiTraccs.GUI.exe starts WikiTraccs.Console.exe to perform the actual migration. Could you please check that WikiTraccs.Console.exe is unblocked? You can find it in the WikiTraccs.Console folder.

Please perform the following steps:

  1.  Open Microsoft Windows Explorer to locate WikiTraccs.Console.exe
  2.  Select WikiTraccs.Console.exe with the right mouse button and choose Properties
  3.  Choose Unblock in the lower right corner of the resulting dialog(*)
  4.  Select OK to close the dialog

(*) If the Unblock button or option is not present, the file is not blocked.

Let me know if that helps.
